name: Update Blog Posts

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 15 * * *'

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install feedparser gitpython

    - name: Run script
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: python scripts/update_blog.py
